version: "3.7"

services:
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=quest
      - RABBITMQ_DEFAULT_PASS=quest
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - project-network


  central:
    restart: always
    build: ./central_microservice/
    ports:
        - "9000:9000"
    networks:
      - project-network

  gateman:
    restart: always
    build: ./gateman_microservice/
    ports:
        - "9001:9001"
    networks:
      - project-network

networks:
  project-network:
    driver: bridge